### ISSUE TITLE
Exclude the roles editor and author

### ISSUE THREAD

**Issue by metmarkosaric** [plausible/wordpress#11]
"Would be great if there's also an option to exclude the roles editor and author"

([feature request via Twitter](https://twitter.com/flowdee/status/1338413125079605249))

**Comment by sbw** [comment]
Good suggestion.  Maybe a generalized setting to control all roles?

**Comment by metmarkosaric** [comment]
Yeah, probably best for this to become part of that same setting which now allows you to track or exclude admin. Don't think it's necessary to separate these. That same setting could simply track or exclude admins, editors and authors all in one. 

Unless someone has a very good reason to separate these roles...

**Comment by flowdee** [comment]
In general, you don't want to include people who actively work on your project and also have access to the admin area. This would include the roles: admin, editor, author.

So I think a general setting would fit as well.

**Comment by mehul0810** [comment]
Closing this issue as this issue has been resolved in PR https://github.com/plausible/wordpress/pull/51

**Comment by metmarkosaric** [comment]
New WordPress plugin release is now out! See https://wordpress.org/plugins/plausible-analytics/

You can now exclude different user roles from being tracked
