### ISSUE TITLE
Page load of WP Homepage immediately triggers an incomplete API Event

### ISSUE THREAD

**Issue by oliveratgithub** [plausible/wordpress#111]
With the newest Plugin version (v 1.2.6) I am seeing an issue on my WP blogs homepage (initial site url) that an invalid XHR request to plausible.io/api/event is triggered, causing a 404 Error. The reference of the requests points to the `plausible.js` JavaScript on Line 757.

<img width="2022" alt="Screenshot 2023-04-05 at 20 15 47" src="https://user-images.githubusercontent.com/280207/230169298-6df9cac4-1aed-488e-a67f-edfa7da3f341.png">

```
Summary
URL: https://plausible.io/api/event
Status: 400
Source: Network
Address: 138.199.37.227:443
Initiator: 
plausible.js:1:757

Request
:method: POST
:scheme: https
:authority: plausible.io
:path: /api/event
Accept: */*
Accept-Encoding: gzip, deflate, br
Accept-Language: en-GB,en;q=0.9
Connection: keep-alive
Content-Length: 119
Content-Type: text/plain
Host: plausible.io
Origin: https://swissmacuser.ch
Referer: https://swissmacuser.ch/
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: cross-site
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.5 Safari/605.1.15

Response
:status: 400
Access-Control-Allow-Credentials: true
Access-Control-Allow-Origin: *
application: 10.0.1.2
Cache-Control: must-revalidate, max-age=0, private
cdn-cachedat: 04/05/2023 18:16:34
cdn-edgestorageid: 860
cdn-proxyver: 1.03
cdn-pullzone: 682664
cdn-requestcountrycode: CH
cdn-requestid: f87fe1c807e09138bb4fa99c1078d0c2
cdn-requestpullcode: 400
cdn-requestpullsuccess: True
cdn-uid: 153cb5b1-399a-48ef-b5bf-098c03770254
Content-Length: 40
Content-Type: application/json; charset=utf-8
Date: Wed, 05 Apr 2023 18:16:34 GMT
permissions-policy: interest-cohort=()
Server: BunnyCDN-DE1-860
x-request-id: F1McqB5pYIZvKHsHIPoJ

Request Data
MIME Type: text/plain
Request Data: 
```

**Comment by Dan0sz** [comment]
I see you're using WP-Optimize. Does the issue also occur when JS optimization is disabled in that plugin?

Furthermore, could you share screenshots of your settings in the Plausible plugin?

**Comment by oliveratgithub** [comment]
> I see you're using WP-Optimize. Does the issue also occur when JS optimization is disabled in that plugin?

Oh, it indeed is related to WP-Optimize! I added a whitelist for `plausible.js` and the 404 API event is gone!
Might then be something to tackle along with #49 ?

```
Exclude JavaScript from processing
/plausible.js
```

**Comment by Dan0sz** [comment]
Will do!
