### ISSUE TITLE
Enable/Disable Plausible Analytics on the WP Admin toolbar

### ISSUE THREAD

**Issue by bogplau** [plausible/wordpress#113]
A quick way to add/remove Plausible Analytics from the WP admin toolbar would be helpful. 

> I just updated the Plausible Analytics plugin to the latest version, and noticed that it now adds a link to the top WP Admin bar.
> 
> Would it be possible for you to add a setting to remove it?
> 
> My admin bar is already crowded as it is, and accessing my analytics from there is not something that's super useful in my case.
> 

(received via email)

**Comment by sunnyt7** [comment]
I was the one who sent in this ticket. I'd really appreciate the ability to remove the Plausible link from the admin bar.

I can see how it'd be helpful for some users, but I don't imagine I'll be accessing my analytics this way. And in my opinion, the admin bar should be reserved for essential functionality (like editing a template or purging cache).

So at least having the option to remove it would be great 🙂
