### ISSUE TITLE
Allow to put a completely custom domain

### ISSUE THREAD

**Issue by Aviortheking** [plausible/wordpress#12]
While using First party domain is efficient, I use for my non-Wordpress sites a single domain for every websites ex:
- site1.com > stats.site-master.com
- site2.com > stats.site-master.com
- etc

It would be awesome to be able to customize more for the Wordpress plugin than just the subdomain name
![image](https://user-images.githubusercontent.com/15822031/104896986-23698e80-5978-11eb-8c37-11851058e194.png)

**Comment by mehul0810** [comment]
@Aviortheking Just to understand better. Do you want us to support WordPress Multisite with subdomains as well as subdirectory?

**Comment by Aviortheking** [comment]
kinda, I use one domain for the analytics and others domains for all my websites

**Comment by mehul0810** [comment]
@Aviortheking I have taken a look on the Plausible Analytics plugin settings and I noticed that you can achieve this by implementing it as follows:

1. Domain Name: Change to `site-master.com`.
2. Custom Domain: Change to `stats` or whatever you want to set.

Following the steps will make sure that the custom domain called is `stats.site-master.com`. You can do this for any number of sites. For example, to develop and test Plausible Analytics plugin, I have created a local site with url: `plausible.test`. But, I use domain name `trendyknow.com` and custom domain `stats.trendyknow.com`.

Let me know if you have any questions.

**Comment by Aviortheking** [comment]
this won't works as Plausible will put the datas on the Domain Name item and not on the real domain ex
I set Domain Name to site1.com and the custom Domain to stats.site-master.com
When I go to Plausible datas are being added to site-master.com while it should have added them to site1.com

**Comment by metmarkosaric** [comment]
thanks! i'm closing this as we will remove support for custom domains in the next major version of the plugin. we now [recommend a proxy for all](https://plausible.io/docs/proxy/introduction) and will be introducing a proxy by default to the plugin instead
