### ISSUE TITLE
Warning: Attempt to read property "post_name" on null

### ISSUE THREAD

**Issue by aanndryyyy** [plausible/wordpress#120]
Got `Warning: Attempt to read property "post_name" on null` reported when custom theme opened `404.php` template at `plugins/plausible-analytics/src/Includes/Actions.php` on Plausible WP plugin version 1.2.6.

Line 103:
https://github.com/plausible/wordpress/blob/0cdaadd0993b06e748918dd6989eca3fc1d45864/src/Includes/Actions.php#L97-L106

404.php contents:
```php
<?php
/**
 * 404 template.
 */

declare(strict_types=1);

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

\get_header();
?>

<main><!-- Some HTML --></main>

<?php
\get_footer();
```

Link in HTML when logged in:
<img width="1071" alt="image" src="https://user-images.githubusercontent.com/1809802/232105342-5d3ec54b-35fa-4f08-9623-466b0a556335.png">

Sentry report:
<img width="997" alt="image" src="https://user-images.githubusercontent.com/1809802/232104957-3179a734-ddf6-40e9-a4cb-3d15cfed55d8.png">

**Comment by Dan0sz** [comment]
Thanks for the comprehensive bug report! A fix for this was already merged to develop in https://github.com/plausible/wordpress/pull/90 so it'll be fixed in the next release!
