### ISSUE TITLE
Naming of Setting is misguiding

### ISSUE THREAD

**Issue by larsschellhas** [plausible/wordpress#121]
Just wanted to let you know that the naming of the setting "Track analytics for user roles" is essentially misleading, as you select the roles that should not be tracked.
I would just recommend to change the name here to "Exclude user roles from tracking" or something like that.

![image](https://user-images.githubusercontent.com/14281234/235356934-f7b018df-1db2-4023-abc4-83c743c83af2.png)

**Comment by Dan0sz** [comment]
Hi!

The option should do exactly what it says; allow you to select the user roles that should be tracked.

You're not supposed to select those roles you wish to exclude. If that's how it works now, then that's a bug and in that case: please share a screenshot of how you currently have it setup.

**Comment by larsschellhas** [comment]
Ah... Hm... I'm gonna check that.

I was previously under the impression that I had disabled tracking of administrators.

And when I read the note today I though it would be saying "select which to exclude". But probably it's not an error then. Gonna check tomorrow or the day after.

**Comment by metmarkosaric** [comment]
perhaps we can consider doing it the other way around in the future (track everyone by default and allow people to manually untick those they don't want tracked) but right now it works the way it is intended and the way i think it works best for most people (nobody is tracked by default and you manually tick those roles you want to track)

**Comment by Dan0sz** [comment]
I'd leave it like this, @metmarkosaric. As a user, I think I'd be very unpleasantly surprised if me and my other colleagues were counted into the stats. I feel this is better as an opt-in (like it's now) than an opt-out.
