### ISSUE TITLE
Added custom user roles seem to not be tracked

### ISSUE THREAD

**Issue by stormrage-project** [plausible/wordpress#125]
It seems, that added user roles are not tracked in the Plausible Wordpress plugin. Some weeks ago, I added another role (even cloned the subscriber role and just gave it another name in this case) and logged-in pageviews aren't tracked anymore.

I noticed this, because my register and login plugin logs the user in automatically and gets redirected to a page, which I'm tracking as a goal in Plausible. The page visits of that goal aren't tracked anymore.

**Comment by Dan0sz** [comment]
The fix to this would be to replace the current list of default roles with a list of all roles present in the configuration. That'll allow you to select which roles to track, even if they're custom user roles.

Thanks for notifying us!

**Comment by stormrage-project** [comment]
@Dan0sz Is there a workaround for the meantime?

**Comment by Dan0sz** [comment]
This PR takes care of this: https://github.com/plausible/wordpress/pull/129

@stormrage-project I'm sorry, but no workaround available in the meantime.

**Comment by metmarkosaric** [comment]
this is now live with the just released version 1.3
