### ISSUE TITLE
Is there a smart solution to cache?

### ISSUE THREAD

**Issue by metmarkosaric** [plausible/wordpress#13]
Had a case where the user enabled the custom domain functionality before it was actually ready to use. And then was trying to remove the functionality without any luck. The cache plugin was installed (LiteSpeed Cache in this case) and Plausible default script only started working again when the user purged the cache. Not sure if there's a way to purge the cache by any change in our plugin or if there's any other solution to this issue that other plugins use? Basically changes in our plugin only start when you purge the cache.

**Comment by mehul0810** [comment]
@metmarkosaric As there are lots of caching plugins with WordPress, I would recommend purging cache is something handled by the caching plugin itself. Also, such scenario might also happen when a CDN is used which also cache content. So, best way to avoid such are:
1. Let users know by adding a question and solution to it on the FAQ section of the plugin
2. Add the similar information in the Custom Domain settings description.

**Comment by metmarkosaric** [comment]
makes sense Mehul! i've already added this to the instructions on our site but will add it to readme.txt too
