### ISSUE TITLE
Proxy setting not working with self-hosted Plausible

### ISSUE THREAD

**Issue by c-heine** [plausible/wordpress#134]
Using the WordPress plugin with self-hosted Plausible.

As soon as I click to use the proxy, I don't get any data anymore.

Is that working as intended?

**Comment by metmarkosaric** [comment]
thanks for reporting @ice-man! as a self-hoster you already run the script as a first party connection from your domain name by default so the proxy is not needed in your case. the proxy is a way for people that use our managed hosting on plausible.io domain so they can run the script as a first party connection from their domain too

**Comment by th0rgall** [comment]
Hello, I have the same issue. No event requests are sent and no data appears.

> as a self-hoster you already run the script as a first party connection from your domain name by default so the proxy is not needed in your case

It's true that it is a first-party connection, but the proxy is still needed: uBlock Origin at least uses a EasyPrivacy rule that filters out any `/plausible.js` paths, which are used by the plugin when the the proxy is not enabled.

![CleanShot 2023-06-07 at 13 31 19@2x](https://github.com/plausible/wordpress/assets/11543641/98f17236-b111-4bdd-8e09-32deceb1b5c0)

I suppose the proxy could resolve this when it generates a random endpoint, as described in the plugin settings:

> The proxy uses WordPress' API with a randomly generated endpoint, starting with https://blog.welcometomygarden.org/wp-json.

But I also understand that fixing self-hoster bugs is not a priority. For now, I'll have to live with adblockers on this particular site.

**Comment by Dan0sz** [comment]
@th0rgall makes a good point, @metmarkosaric. What do you think?

**Comment by tenfourty** [comment]
I have the same issue with my self hosted plausible site. I think there is a bug here regardless because if you don't intend to support self-hosted instances with this feature you should probably grey out the option to have a proxy when the user has put in the url of their self-hosted instance.

**Comment by metmarkosaric** [comment]
makes sense @tenfourty! we've just made this clearer by greying out the proxy and adding a note about it when self-hosting is enabled. it will go live in the next release. thanks for the feedback!

**Comment by tenfourty** [comment]
Thanks, I'm disappointed you didn't want to make a quick fix to support self-hosted with the proxy, would you accept a pull request to add that functionality?

**Comment by Daniel15** [comment]
To me it seems like all you'd need to do is replace this hard-coded `https://plausible.io/api/event` URL with the correct domain when self-hosting is enabled:

https://github.com/plausible/wordpress/blob/66f35993a9911c2caff1431cc09b6148afaa83c3/src/Includes/Proxy.php#L112-L115

The proxy for the JS already seems to handle self-hosting fine, and the same logic could be reused for the /api/event proxy too:

https://github.com/plausible/wordpress/blob/66f35993a9911c2caff1431cc09b6148afaa83c3/src/Includes/Helpers.php#L67-L76

**Comment by tenfourty** [comment]
Good spot @Daniel15 It really felt like this was an active disabling of self-hosted features that took more code to disable it than to support it!
I don't have the time at the moment but I do plan to write a PR to put this functionality in (if someone doesn't beat me to it).
