### ISSUE TITLE
conflict with SG Optimizer

### ISSUE THREAD

**Issue by thbeach** [plausible/wordpress#136]
Hi Guys,
I have a site using plausible analytics that needs to show up accurately. https://firstfleetfellowship.org.au
This site used to have something like 20 000 visitors a month, and now only shows something like 20. I added the plugin again, as it had disappeared, so I am unsure what is happening. It is hosted on siteground and uses SG optimiser, and I can use WPRocket if needed. The attached is from November 22 to date.
<img width="1101" alt="CleanShot 2023-06-20 at 14 43 31@2x" src="https://github.com/plausible/wordpress/assets/137140549/c562a818-d39a-4cf5-b8d2-111330946b83">
Any thoughts?
Cheers
Nigel

**Comment by metmarkosaric** [comment]
hi @thbeach! i checked your site and cannot see our script on it which explains why the stats are not being tracked. there might be a plugin conflict. have you cleared the cache? what version of our plugin are you using? and is the proxy enabled in the plugin? as an alternative do try WP Rocket instead and see if that works better

**Comment by thbeach** [comment]
have added wp rocket and can now see plausible in the script, I have enabled the proxy too, so I am hoping that it is working ok, I can see live visitors now, so I think we are back to normal. Thanks for your help.
cheers
Nigel

**Comment by metmarkosaric** [comment]
great, thanks for the update @thbeach! i'll keep this one open so @Dan0sz can have a look at fixing the conflict with SG Optimizer

**Comment by Dan0sz** [comment]
Hi @thbeach,

Thanks for reporting this issue. I'm having a hard time replicating this on my local machine. Would you mind sharing your settings in SG Optimizer?

Thanks!

**Comment by metmarkosaric** [comment]
closing this for now as we cannot replicate but we can always reopen if we get more info
