### ISSUE TITLE
Latest update breaks domains

### ISSUE THREAD

**Issue by ice-man** [plausible/wordpress#137]
That latest updates breaks the domain column in the database which results in a 500 error when trying to look at the stats.

I just rolled back the installation but after receiving updates through WatchTower, it's the same as before

** (exit) an exception was raised:
    ** (Postgrex.Error) ERROR 42703 (undefined_column) column g0.domain does not exist
    query: SELECT TRUE FROM "goals" AS g0 WHERE (g0."domain" = $1) LIMIT 1
        (ecto_sql 3.8.3) lib/ecto/adapters/sql.ex:932: Ecto.Adapters.SQL.raise_sql_call_error/1
        (ecto_sql 3.8.3) lib/ecto/adapters/sql.ex:847: Ecto.Adapters.SQL.execute/6
        (ecto 3.8.4) lib/ecto/repo/queryable.ex:221: Ecto.Repo.Queryable.execute/4
        (ecto 3.8.4) lib/ecto/repo/queryable.ex:19: Ecto.Repo.Queryable.all/3
        (ecto 3.8.4) lib/ecto/repo/queryable.ex:130: Ecto.Repo.Queryable.exists?/3
        (plausible 0.0.1) lib/plausible_web/controllers/stats_controller.ex:66: PlausibleWeb.StatsController.stats/2
        (plausible 0.0.1) lib/plausible_web/controllers/stats_controller.ex:1: PlausibleWeb.StatsController.action/2
        (plausible 0.0.1) lib/plausible_web/controllers/stats_controller.ex:1: PlausibleWeb.StatsController.phoenix_controller_pipeline/2

**Comment by metmarkosaric** [comment]
hi @ice-man! this doesn't seem related to the wordpress plugin? if this is about your self-hosted instance, please post in our self-hosted community forum https://github.com/plausible/analytics/discussions/categories/self-hosted-support
