### ISSUE TITLE
Issue with the custom domain

### ISSUE THREAD

**Issue by metmarkosaric** [plausible/wordpress#14]
Had a case with the user enabling the custom domain functionality in the plugin before it's ready to use (for instance while the DNS/CNAME changes are in progress as sometimes it takes minutes while sometimes hours). Normally in our docs we ask the user never to change the code on their site until they can verify that the script is being loaded from the custom domain (yoursubdomain.yourdomain.com/js/index.js). 

I wonder if there's a way to do something like this in the plugin to prevent the user enable the custom domain before it's ready to use? Or to somehow fall back to the default script if the custom domain is not ready and then switch to using the custom domain when the CNAME change is ready?

**Comment by mehul0810** [comment]
@metmarkosaric I will double-check on this. I think that checking the url availability with `file_get_contents` or some better way would help us do this. We need to check it every hour or every 15 mins with a cron job for the status. Once we get that the url for custom domains are working we can then auto-switch to custom domains url.

**Comment by metmarkosaric** [comment]
that seems like a good way to do this! in most cases the integration takes 2-3 minutes and in some cases it may take up to 4 hours or so all depending on the DNS process. thanks @mehul0810!

**Comment by metmarkosaric** [comment]
closing this as custom domains are no longer that relevant and we will remove them from the plugin
