### ISSUE TITLE
Integrate Plausible Revenue Tracking

### ISSUE THREAD

**Issue by masteradhoc** [plausible/wordpress#141]
See https://plausible.io/docs/ecommerce-revenue-tracking

Would be amazing to get a builtin Version into the Plugin for those that need it.

**Comment by metmarkosaric** [comment]
thanks @masteradhoc! this is done in version 2.0 which is now out! it requires you to manually send the revenue data as explained here https://plausible.io/wordpress-analytics-plugin#how-to-track-ecommerce-revenue. we plan to do something more automated with the support of Woocommerce in the future as listed in your other thread here https://github.com/plausible/wordpress/issues/142
