### ISSUE TITLE
Integrate WooCommerce Revenue Tracking

### ISSUE THREAD

**Issue by masteradhoc** [plausible/wordpress#142]
Additional to #141 this enhancement request also asks for an easy integration of the woocommerce code visible here: https://plausible.io/docs/ecommerce-revenue-tracking

If WooCommerce is active would be nice to also show a checkbox to activate the code & woo tracking.

**Comment by metmarkosaric** [comment]
thanks @masteradhoc! we plan to add both of these. stay tuned!

**Comment by Dan0sz** [comment]
FYI: this feature is scheduled for release in v2.1.0.

**Comment by ryanhalliday** [comment]
Hate to be a pain but when is v2.1.0 coming out? Can't see it as a milestone [here](https://github.com/plausible/wordpress/milestones?state=open). 

If there is anything blocking it I'd be happy to help out?

**Comment by Dan0sz** [comment]
This is added in the latest beta of v2.1.0. A stable release is scheduled to be released before the end of this month.

**Comment by metmarkosaric** [comment]
**Update:** Latest version of our WordPress plugin introduces a WooCommerce integration for revenue attribution tracking. The WooCommerce integration automatically sets up several custom events (including add to cart and remove from cart), revenue tracking for completed purchases, custom properties (including product name, price and total cart items) and a checkout funnel to help you understand the cart abandonment rate. No need to manually set up anything nor to edit your code. Details at: https://plausible.io/wordpress-analytics-plugin
