### ISSUE TITLE
Plausible wont show in WP dashboard

### ISSUE THREAD

**Issue by teeore** [plausible/wordpress#143]
Plausible wont show in WP dashboard. I've followed all the instructions and even recreated the shared link twice. It says 'plausible.io unable to connect'. Pls see attached image.
![CleanShot 2023-07-09 at 18 49 49@2x](https://github.com/plausible/wordpress/assets/4422157/475dfd38-96e4-44fb-a848-d32913ddb7b1)

**Comment by metmarkosaric** [comment]
hi @teeore! are you trying to embed a password protected shared link? this error normally shows for that. try to create a new non-password protected shared link and try to embed that one. you can read more here https://plausible.io/wordpress-analytics-plugin#how-to-view-your-stats-directly-in-your-wordpress-dashboard
