### ISSUE TITLE
WP Proxy Fails due to mixed content

### ISSUE THREAD

**Issue by digisz** [plausible/wordpress#150]
after enabling the proxy in the WP plugin I got the following error and the script was no longer loaded.

Mixed Content: The page at 'https://mywebsite.com/' was loaded over HTTPS, but requested an insecure script 'http://mywebsite.com/wp-content/uploads/xxxxxxxxxxx/xxxxxxx.js?ver=1689601997'. This request has been blocked; the content must be served over HTTPS.

**Comment by Dan0sz** [comment]
Hi!

Can you check your WordPress URL and Home URL settings under WP Admin > Settings > General?

Do both URLs start with `https://`?

If so, is your site served from a reverse proxy?

**Comment by digisz** [comment]
Hi!

Just checked, both start with https://  . I did however only change this after installing the plausible plugin which gave me an idea and helped solve the problem.

1. deactivate and reactivate plausible plugin: no success
2. delete and reinstall plausible plugin, reenable proxy: success

**Comment by Dan0sz** [comment]
Ok, there you go! Happy you got it resolved. Probably just toggling the Proxy would've fixed it, come to think of it.

**Comment by metmarkosaric** [comment]
nice, glad this was easy to fix! closing this for now
