### ISSUE TITLE
Hide the Analytics entry from showing in the sidebar if you don't enable embed in the plugin settings

### ISSUE THREAD

**Issue by oldrup** [plausible/wordpress#156]
I guess you added the Administrator checkbox user for aesthetics, but disabled it because - why wouldn't you allow admins to use the analytics dashboard? 

![image](https://github.com/plausible/wordpress/assets/17141205/49cab773-ca58-4498-92ee-08edf3396cc3)

I tell you why. Content Security Policies ;) Our policy, does not allow external iframes, within the wordpress dashboard, and selecting the menu item, just results in an error:

![image](https://github.com/plausible/wordpress/assets/17141205/9b4c183e-59fd-4655-b2c4-7c0fe033b221)

Therefore, I would actually prefer to be able to disable the embedded analytics dashboard completely. Now, the administrator option has been added - that's great - but then you disabled it!😭

So close!

I suggest, you enable the checkbox, trusting the administrator to choose whether the analytics dashboard embed should be enabled or not 🤗

**Comment by metmarkosaric** [comment]
thanks @oldrup! what we can probably do is to hide the Analytics entry from showing in the WP sidebar under Dashboard if you don't enable the embed functionality in the plugin settings

**Comment by oldrup** [comment]
Yeah - customers and their conflicting ideas, right? 😂

I actually agree, that it did look a bit off with the admin in one row and not the other, and It's no big deal at all - I know what's going on, and Editor roles will not see the dashboard in the first place, but I really like Plausible for how well it works, and I'd love it to be really pretty as well ;)

**Comment by Dan0sz** [comment]
> thanks @oldrup! what we can probably do is to hide the Analytics entry from showing in the WP sidebar under Dashboard if you don't enable the embed functionality in the plugin settings

Good one. Let's make it work like that.

**Comment by Dan0sz** [comment]
Just came across this one again. The next release will hide the Analytics entry from the Dashboard menu if View Stats is disabled.
