### ISSUE TITLE
Analytics Tab in wp-admin not showing when using Adblocker

### ISSUE THREAD

**Issue by masteradhoc** [plausible/wordpress#158]
When using f.e. uBlock Origin the Analytics Tab in wp-admin is empty. if you deactivate it works perfectly.
Any chance we can use a proxy feature to also display this everytime?

![image](https://github.com/plausible/wordpress/assets/6242098/0596fead-42ef-4d6e-800c-285cc64f89ee)

![image](https://github.com/plausible/wordpress/assets/6242098/7ec6ac88-f8c0-47d5-9a6d-bbba52d80256)

**Comment by Dan0sz** [comment]
That's because it's loaded in an iframe. I'd have to discuss the possibilities of this with @ukutaht.

**Comment by metmarkosaric** [comment]
there's not much we can do about this unfortunately. the best action is to disable the adblock on your own site. in plugin version 2.0 which is out now, we have added a note in case we detect an adblocker to tell you to disable it to view the dashboard within your WP
