### ISSUE TITLE
Add pageview-props extension to script

### ISSUE THREAD

**Issue by JUVOJustin** [plausible/wordpress#165]
I just added my custom pageview property, so the script tag looks like this: 

`<script defer="" data-domain="xxx.me" data-api="https://plausible.io/api/event" event-creator="6494126149978adbb4433382" src="https://plausible.io/js/plausible.outbound-links.file-downloads.tagged-events.hash.js?ver=1.3.4" id="plausible"></script>`

Even with every option enabled, it seems the required `pageview-props` script extension is not added. Related documentation: https://plausible.io/docs/custom-props/for-pageviews

I tried finding the part where the WordPress settings are added, and the final script name is build, without success :D
I will happily provide a PR if you could send me in the right direction.

**Comment by JUVOJustin** [comment]
I found it and made it working 🎉.

Just for completeness, I will add my example script to add any acf field as pageview prop:

```php
// Add ACF Field as prop to pageviews
add_filter('plausible_analytics_script_params', function($params) {

	// Get field value
	$value = get_field('awesomefield');

	// Exit early if empty
	if (empty($value)) {
		$params;
	}
	
	// Add prop to script tag
	$params .= " event-awesomefield='$value'";
	return $params;
});
```

**Comment by Dan0sz** [comment]
This feature (and your PR) will be added in 2.0.0, which is the current release we're working on.

Thanks for your contribution!
