### ISSUE TITLE
2.0.0 Update makes WP Admin Stuck

### ISSUE THREAD

**Issue by ManaSiWibi** [plausible/wordpress#172]
Recently updated to the latest version, now the admin page is stuck and always redirected to https://example.com/wp-admin/options-general.php?page=plausible_analytics#welcome_slide

Anyone can reproduce the issue?

Plausible Plugin: set up using a self-hosted option
$wp_version = '6.4.3';

**Comment by ManaSiWibi** [comment]
Network log: 
`GET	https://example.com/wp-admin/index.php 302`
Response header: location: https://example.com/wp-admin/options-general.php?page=plausible_analytics#welcome_slide

It redirected to 
`GET	https://example.com/wp-admin/options-general.php?page=plausible_analytics 200`

**Comment by Dan0sz** [comment]
Hi!

Are you seeing any errors in your console (press F12 to open it in your browser)

**Comment by ManaSiWibi** [comment]
Nope, nothing.

Additional information I updated 4 plugins (Elementor, Elementor Pro, Polylang, Plausible), as soon the site was updated, the admin dashboard always redirected to the Plausible plugin page.

I have access to the WP server, if there is a way to debug it directly on CLI, kindly let me know how to do it.

**Comment by Dan0sz** [comment]
Ah, nevermind. Think I found it.

Can you try installing [this test-release](https://github.com/plausible/wordpress/releases/download/2.0.1-beta1/plausible-analytics.zip) to see if that resolves your issue?

**Comment by ManaSiWibi** [comment]
That does the trick!

Thanks for the apt response @Dan0sz

**Comment by Dan0sz** [comment]
Great, will release a 2.0.1 now. Thanks for getting back to me!
