### ISSUE TITLE
401 Error when changing Settings after updating

### ISSUE THREAD

**Issue by JUVOJustin** [plausible/wordpress#173]
I just updated my website´s plausible plugin to the latest version and received 401 errors when updating any settings:
https://www.loom.com/share/76465a2953a7480f927942bf87b2480a?sid=c6d9c0e8-7351-4258-a2ee-dd7bcfea5df3

**Comment by metmarkosaric** [comment]
hi @JUVOJustin! from watching your Loom, I can see that you're creating a Stats API key and this is not needed for the Wordpress plugin. there's a link directly in the WP plugin that takes you to a brand new section where you can create a new plugin token API. that's the one you need to use in the plugin. can you please try that?
