### ISSUE TITLE
View Analytics doesn't work on the self-hosted option.

### ISSUE THREAD

**Issue by ManaSiWibi** [plausible/wordpress#179]
Although the Self-Hosted's Shared link is already filled, the View Analytics page shows "Please enter your Shared Link under [Self-Hosted Settings](https://example.com/wp-admin/options-general.php?page=plausible_analytics#is_shared_link)."

Plausible version 2.0.2.

**Comment by Dan0sz** [comment]
Please try 2.0.3, which is about to be released in 3... 2... 1...
