### ISSUE TITLE
Use with self-hosted

### ISSUE THREAD

**Issue by binaryfire** [plausible/wordpress#18]
Hi guys,

Can this be used with self-hosted Plausible installations? I find anything in the settings page or docs.

It would be great if you could add this. No need to add it to the settings page- you could just add some wp-config.php variables we can use to specify all the fields needed to connect to a self-hosted install. If these variables are specified, the wp-admin settings page could be automatically disabled,

**Comment by metmarkosaric** [comment]
thanks @binaryfire! you can already do this. just click on "self hosted" on the plugin settings page.

**Comment by binaryfire** [comment]
Ooops, totally mised that :P

Thanks!
