### ISSUE TITLE
2.0.0 On-boarding wizard prompting insufficient permission errors.

### ISSUE THREAD

**Issue by Alex-Hay** [plausible/wordpress#183]
When updating to 2.0.0, all users are being prompted to complete the new on-boarding wizard. The sites had run through the previous setup wizard in the past, but the main issue is that users with insufficient permissions (editor) are being redirected to the on-boarding URL, causing this error.

```You do not have sufficient permissions to access this admin page. Reason: The current user doesn't have the "manage_options" capability that is required to access the "Settings" menu item.```.

This has prompted a lot of 'My website is broken' client emails'.

**Comment by Dan0sz** [comment]
Hi!

Just pushed 2.0.5 which should resolve this issue.
