### ISSUE TITLE
If proxy is enabled and the file fails to create, there is no error handling

### ISSUE THREAD

**Issue by jmstopper** [plausible/wordpress#184]
Hi Support

I recently migrated a site and the permissions were not set correctly for WordPress (PHP and plugins) to be able to create files in the uploads directory.

When activating the proxy setting in the plugin, the file is meant to be created in the uploads directory, but if this fails, there is no error handling to suggest that the file was not created.

Sorry I don't have a screenshot for this one

**Comment by metmarkosaric** [comment]
thanks for reporting @jmstopper! version 2.0.6 that just went out an hour ago should have better error handling and also more readable error messages.
