### ISSUE TITLE
PHP Parse error

### ISSUE THREAD

**Issue by valentin-anamorphik** [plausible/wordpress#186]
Hi,

I have this error (debug.log) when activating the plugin. Error 500.

`[23-Feb-2024 10:34:08 UTC] PHP Parse error:  syntax error, unexpected ')' in /wp-content/plugins/plausible-analytics/src/Admin/Settings/API.php on line 142`

- WP : 5.6.13
- Multisite is active

Thanks.

**Comment by Dan0sz** [comment]
Which PHP version are you using?

**Comment by valentin-anamorphik** [comment]
7.2.34

https://github.com/plausible/wordpress?tab=readme-ov-file#minimum-requirements

**Comment by Dan0sz** [comment]
Okay, and just to be sure; you're running the latest version?

**Comment by Dan0sz** [comment]
FYI; we're releasing 2.0.6 on Monday, try it, cause it might response your issue. If it doesn't, please let me know and see if the line number changed in the error.

**Comment by Dan0sz** [comment]
Nevermind! I just had a look at the code again and noticed the trailing comma after the last parameter in the `sprintf()` function call. Which isn't yet supported in PHP 7.2 and lower. 

It'll be fixed in 2.0.6 which'll be released next Monday. If you don't want to wait, you can install the pre-release manually, which is available [here](https://github.com/plausible/wordpress/releases/download/2.0.6/plausible-analytics.zip).

**Comment by valentin-anamorphik** [comment]
> Nevermind! I just had a look at the code again and noticed the trailing comma after the last parameter in the `sprintf()` function call. Which isn't yet supported in PHP 7.2 and lower.
> 
> It'll be fixed in 2.0.6 which'll be released next Monday. If you don't want to wait, you can install the pre-release manually, which is available [here](https://github.com/plausible/wordpress/releases/download/2.0.6/plausible-analytics.zip).

[26-Feb-2024 08:16:32 UTC] PHP Parse error:  syntax error, unexpected 'array' (T_ARRAY), expecting function (T_FUNCTION) or const (T_CONST) in /wp-content/plugins/plausible-analytics/src/Client/lib/Model/Capabilities.php on line 84

I think your plugin requires PHP 7.4 or PHP 8.

**Comment by Dan0sz** [comment]
Ah, yes, you're right. The API client we added in 2.0 is a 3rd party library and I just noticed that PHP 7.4 or higher is required for it to run.

In the next release I'll raise the required PHP and WP versions.

Sorry for the hassle.
