### ISSUE TITLE
Allow settings to be defined in wp-config.php

### ISSUE THREAD

**Issue by binaryfire** [plausible/wordpress#19]
It would be great to have the option of defining settings win wp-config.php. Several plugins offer this, eg: https://wpmailsmtp.com/docs/how-to-secure-smtp-settings-by-using-constants/. It's great for devs and better for security when dealing with tokens etc.

**Comment by mehul0810** [comment]
@binaryfire Curious to know which constants or settings you want to be defined inside `wp-config.php`. Can you elaborate more on this?

**Comment by metmarkosaric** [comment]
thanks! i'm closing this as there's no plan to do this. we'd prefer to have the plugin be as simple and as easy as possible to use for all. all the settings and features we want to allow in the plugin should have an easy way to enable/disable in the UI
