### ISSUE TITLE
Constants to define Modules globally

### ISSUE THREAD

**Issue by masteradhoc** [plausible/wordpress#223]
As we are managing a huge number of sites it would be amazing if we could control the functionality of the plausible plugin easier with constants. Like this new features could be rolled out much faster & new sites are setup even faster!

Features i could see useful to be controlable with constants:
- Enhanced measurements
- View Stats in WordPress
- Tracked User Roles
- Embed visible for User Roles

Thanks

**Comment by Dan0sz** [comment]
Hi @masteradhoc,

Thanks for the suggestion. Can you post an example of what you'd like to achieve?

**Comment by masteradhoc** [comment]
@Dan0sz Something like this: https://wpmailsmtp.com/docs/how-to-secure-smtp-settings-by-using-constants/
Basically the idea is about to configure the plugin settings listed above over code.
This would help us define this in our custom plugin or wp-config by default and make sure all sites of us have the same settings.

**Comment by Dan0sz** [comment]
There's already [a filter](https://github.com/plausible/wordpress/blob/develop/src%2FHelpers.php#L122) available to force settings. Would that work for you?

**Comment by masteradhoc** [comment]
@Dan0sz Thanks, we'll check that and would let you know in case there is an issue :)
