### ISSUE TITLE
WP Dashboard unresponsive if self-hosted plausible is unreachable

### ISSUE THREAD

**Issue by semanticfire** [plausible/wordpress#224]
Hi,

If a self-hosted version of plausible becomes unreachable, the wordpress dashboard becomes unresponsive.
Depending on the configuration of the web server it can result in HTTP Code 500.

The website itself works flawlessly, the script tags just timeout, but the dashboard seems to wait for a response from the plausible server.

**Comment by Dan0sz** [comment]
I'm aware of this issue, and I'm working on a fix as we speak. I'll push out a beta containing the fix ASAP!
