### ISSUE TITLE
Run analytics through subfolder / proxy

### ISSUE THREAD

**Issue by metmarkosaric** [plausible/wordpress#23]
Rather than instructing people to create a custom domain / CNAME we could run the analytics through a proxy directly using the WordPress plugin. Would be an easier way to get started and very effective in terms of not being blocked by adblockers

**Comment by metmarkosaric** [comment]
We now have instructions on how to proxy our script. See https://plausible.io/docs/proxy/introduction

**Comment by metmarkosaric** [comment]
The intro of automatic proxy by default for all cloud users would mean that we can remove the custom domain functionality from the plugin as the custom domain would no longer be necessary.

**Comment by metmarkosaric** [comment]
Introducing the proxy should also fix the issue we sometimes have with WP Rocket and similar plugins changing our snippet https://github.com/plausible/wordpress/issues/49

**Comment by bdlowery** [comment]
Has proxying plausible been enabled by default on the WordPress plugin? I don't see an option to enable it.

**Comment by metmarkosaric** [comment]
> Has proxying plausible been enabled by default on the WordPress plugin, or is this still a work in progress?

hi @bdlowery! still work in progress. to use a proxy in the meanwhile, you would need to integrate Plausible into your WP site manually

**Comment by Dan0sz** [comment]
https://github.com/plausible/wordpress/pull/123 takes care of this!

**Comment by metmarkosaric** [comment]
proxy is now live with the just released version 1.3
