### ISSUE TITLE
Add prefetch or preconnect to plausible

### ISSUE THREAD

**Issue by benjaminwolkchen** [plausible/wordpress#24]
GTMetrix recommends me, to preconnect or prefetch the Plausible Domain.

[![Screenshot_2021-03-20 GTmetrix Performance Report](https://user-images.githubusercontent.com/42138517/111882296-310db580-89b5-11eb-9310-793e7322a649.png)](https://gtmetrix.com/reports/awesomebible.de/FGQcZiTR/)

**Comment by ukutaht** [comment]
Wouldn't call it an 'important' third-party origin. The page will work fine without the tracker and it's intended to run after everything has been loaded (via the `async` directive).

Adding prefetch or preconnect probably wouldn't hurt though, can't see any downsides.
