### ISSUE TITLE
Toggling the setting for the analytics dashboard doesn't work

### ISSUE THREAD

**Issue by LittleBigThing** [plausible/wordpress#29]
I noticed that the toggle to show your analytics in the WordPress admin doesn't work as expected: toggling it does not influence whether the analytics are shown. Once the shared link is pasted, the analytics are always shown.

![Screenshot 2021-04-21 at 09 22 34](https://user-images.githubusercontent.com/5901923/115514094-0f3d7200-a284-11eb-96f6-e39b81c7678d.png)

There is one effect of the toggle: when no shared link is pasted, the instructions are only shown on the analytics page when the toggle is on. Otherwise, the page is there without instructions.

Plugin version 1.2.

**Comment by mehul0810** [comment]
This issue has been fixed and will be released as a part of version `1.2.1`. Hence, closing this issue.
