### ISSUE TITLE
add support for custom events tracking

### ISSUE THREAD

**Issue by mehul0810** [plausible/wordpress#3]
## User Story
As a user, I want to track custom events in my WordPress website so that I can utilize to see my marketing efforts using Plausible Analytics.

**Note:** Currently, we will go ahead with basic support for WordPress and WooCommerce.

## Acceptance Criteria
- [x] Add the custom event tracking snippet

**Comment by metmarkosaric** [comment]
Note that since this we've also introduced support for custom properties for events tracking. See https://docs.plausible.io/custom-event-goals#using-custom-props

**Comment by mehul0810** [comment]
@metmarkosaric  I am closing this snippet as the custom events tracking snippet is already added. So, anyone can use `plausible()` function to utilize tracking with Javascript. I will also add a new issue which will be an improvement over this issue where we will share that issue URL to users who will let us know what plugin integrations they need which works out-of-the-box for event tracking.
