### ISSUE TITLE
Update to Version 1.2.0 sets wordpress into troubleshooting mode

### ISSUE THREAD

**Issue by ekirschner** [plausible/wordpress#31]
I've tried to update the plugin on two of my wordpress instances. First before updating from wp version 5.6.2 and then after sucessfully updating to 5.7.1. I first thought that the wp update would cause the problem, but I figured out, that the plausible plugin must be the culprit. 

![image](https://user-images.githubusercontent.com/772563/115551597-994d0100-a2ab-11eb-9cc4-a375e109caab.png)

I now did a rollback from backups and will wait for a fix. Any idea how this could happen?

**Comment by ekirschner** [comment]
Fehler-Details
==============
Ein Fehler vom Typ E_PARSE wurde in der Zeile 204 der Datei /home/wp/disk/wordpress/wp-content/plugins/plausible-analytics/src/Admin/Settings.php verursacht. Fehlermeldung: syntax error, unexpected ')'

Error Details
==============
An error of type E_PARSE was caused on line 204 of file /home/wp/disk/wordpress/wp-content/plugins/plausible-analytics/src/Admin/Settings.php. Error message: syntax error, unexpected ')'.

**Comment by metmarkosaric** [comment]
Similar report here mentioning it might have something to do with the PHP version running https://github.com/plausible/analytics/discussions/159#discussioncomment-640173

**Comment by flowdee** [comment]
@metmarkosaric Tip from a WP developer: 

WP officially runs with PHP 5.6.20 so you must make sure that you test it with 5.6 as well. Unfortunately, there are soooooo many outdated sites. Unfortunately, you can't assume that peeps run their sites with PHP 7.4 😄

**Comment by metmarkosaric** [comment]
Thanks! We will release a patch today. Also will create a unit test in future release which will ensure smooth release on all of the platforms also the older ones.

**Comment by mehul0810** [comment]
This issue is fixed and will be released as a part of version `1.2.1` today. Some users with older PHP versions are affected.

**Comment by metmarkosaric** [comment]
Version 1.2.1 has been deployed now with some fixes. Could you check now please @ekirschner?

**Comment by ekirschner** [comment]
@metmarkosaric Great, thank you so much. With 1.2.1 it works like it should. BTW: The two wordpress instances are running under PHP version 7.2, thus not sooo old.
