### ISSUE TITLE
New setting: Control which user role(s) can access the analytics dashboard

### ISSUE THREAD

**Issue by flowdee** [plausible/wordpress#35]
In our case, we want our writers to access the analytics dashboard, so they can see how often which posts get viewed etc.

Right now, only "administrators" can access the analytics page. 

Would be great if you could add a setting which allows us to control which user role(s) can access the page.

**Comment by LittleBigThing** [comment]
+1

I often give people the ‘editor’ role instead of ‘administrator’ to manage their sites, because I don't want them or they’re not interested in installing themes or plugins (and to declutter the admin).

I’d be happy with a **filter to change the capability** needed to view the analytics page (‘edit_pages’ for example instead of ‘manage_options’).

They wouldn't necessarily have the ability to generate a shared link. So the analytics page should only be visible if the shared link is there and the setting in ‘on’ if possible.

**Comment by gbissland** [comment]
+1 same reasons as above. 
Filter would be a good addition. Our clients have editor role as well.

**Comment by masteradhoc** [comment]
+1!

**Comment by mehul0810** [comment]
Thanks for the feedback folks. I have added it to be released with `1.3.0` soon.

**Comment by masteradhoc** [comment]
@mehul0810 any update on the release of 1.3?

**Comment by metmarkosaric** [comment]
hi @masteradhoc! there are no updates at the moment. we are a small team with limited development resources so things take time. we'll update here as soon as there's some news. thanks for understanding!

**Comment by mehul0810** [comment]
Closing this issue as it has been completed and merged to `develop` branch.

### Screenshot
<img width="809" alt="CleanShot 2021-11-28 at 00 20 24@2x" src="https://user-images.githubusercontent.com/1852711/143718703-548cebf9-7231-4835-a6f4-d1a192461b60.png">

**Comment by masteradhoc** [comment]
@mehul0810 any update on this feature? :)

**Comment by mehul0810** [comment]
@masteradhoc I think this has already been worked upon and just pending release. Please wait a couple of weeks and I will get it released asap.

**Comment by masteradhoc** [comment]
@mehul0810 hope your doing good? any update on this release date?

**Comment by Retroike7** [comment]
Any update on the release date for this one?

**Comment by masteradhoc** [comment]
@mehul0810 @metmarkosaric any update on this feature? Quite some time now since it was developed..

**Comment by metmarkosaric** [comment]
hi @masteradhoc! our developers are working on the next version of the plugin and this should be a part of that release. as soon as we have some news, we'll post it on github. thanks for your patience!

**Comment by sascha-bleech** [comment]
It would really be good to get another release out asap. There seems to be a lot of functionality in the develop branch that users are waiting for.

**Comment by metmarkosaric** [comment]
New WordPress plugin release is now out! See https://wordpress.org/plugins/plausible-analytics/

You can now allow selected user roles to access the stats dashboard
