### ISSUE TITLE
Issues with WP Rocket

### ISSUE THREAD

**Issue by metmarkosaric** [plausible/wordpress#38]
Got two reports today and both were solved by disabling WP Rocket plugin. When WP Rocket is enabled, it seems to change our script into something like this which caches the script and hosts it as a first-party connection (happens both with our WP plugin and with the manual integration):

`<script data-minify="1" async defer data-domain="yourdomain.com" src="https://yourdomain.com/wp-content/cache/min/1/js/plausible.js?ver=1621435097"></script>`

**Comment by ukutaht** [comment]
Ah this is probably caused by moving to `docuement.currentScript` in [this commit](https://github.com/plausible/analytics/commit/e80fc7bb8e436089e10582a8aee04f295b69b258).

Potential fixes:
1. Add `data-api='https://plausible.io/api/event'` to the script tag
2. Is there a way to tell WP Rocket to ignore certain files? If it didn't try to cache it, everything would work OK
3. If we figure out a way to get the Plausible plugin to proxy requests, this problem will go away since the endpoint it's trying to send data `https://yourdomain.com/api/event` would exist and forward the data to our backend.

**Comment by metmarkosaric** [comment]
Just got another case now and it was solved by excluding the Plausible script in WP Rocket settings and then clearing the cache. This is how the WP Rocket settings look like: 

![download-3](https://user-images.githubusercontent.com/34340819/118944166-97cb3300-b954-11eb-909b-f7056fe6d0cf.png)

Would be nice if we can fix this as I suspect it could be impacting more people as WP Rocket is one of those very popular plugins people use to optimize the performance of their sites.

**Comment by ukutaht** [comment]
Quickest thing would be for the Wordpress plugin to install the script with the new `data-api` attribute.

Another option seems to be that WP Rocket [does not cache files with query strings](https://docs.wp-rocket.me/article/971-caching-query-strings). So maybe if the script is loaded via `https://plausible.io/js/plausible.js?rocket-cache=false` it would leave our script tag alone?

**Comment by mehul0810** [comment]
@ukutaht Is there any example on where to add the `data-api` attribute and what would be the value of the `data-api` attribute?

**Comment by ukutaht** [comment]
@mehul0810 yes, add `data-api='https://plausible.io/api/event'` to the script tag as follows:

```html
<script data-domain="website-domain.com" data-api='https://plausible.io/api/event' src="https://plausible.io/js/plausible.js"></script>
```

**Comment by iamkingsleyf** [comment]
having same problem

**Comment by ekirschner** [comment]
I closed my own duplicated issue. Following here for a fix.

**Comment by mehul0810** [comment]
@ukutaht Just to double-check before releasing a patch, will the `data-api="https://plausible.io/api/event"` will work for both self-hosted version as well as cloud hosted version?

**Comment by metmarkosaric** [comment]
> @ukutaht Just to double-check before releasing a patch, will the `data-api="https://plausible.io/api/event"` will work for both self-hosted version as well as cloud hosted version?

this latest change for the proxy is not relevant to the self-hosted version. we haven't made any changes to the self-hosted yet

**Comment by ukutaht** [comment]
@mehul0810 No, for self-hosted it would have to POST to `https://${self-hosted-plausible.domain}/api/event`

**Comment by metmarkosaric** [comment]
New version of our plugin is now live and it should fix the WP Rocket issue https://wordpress.org/plugins/plausible-analytics/

**Comment by metmarkosaric** [comment]
We've had several new reports of issues with WP Rocket and similar plugins recently. Even when our plugin is used, the tracking doesn't seem to work in some cases. Here's an example of how our snippet looks like with our WP plugin installed and with WP Rocket optimization on at the same time and the tracking doesn't work:

<script type="rocketlazyloadscript" data-minify="1" async defer data-domain='yourdomain.com' data-api='https://plausible.io/api/event' src='https://www.yourdomain.com/wp-content/cache/min/1/js/plausible.outbound-links.js?ver=1665132125' id='plausible-analytics-js'></script> 

Any ideas on how we can fix this plugin conflict in our plugin in the future @bouchaala-sabri?

**Comment by bouchaala-sabri** [comment]
According to the snippet, it's either the minify or the async defer, I can
test both and force disable the feature via wp-rocket hooks.

**Comment by metmarkosaric** [comment]
nice one @bouchaala-sabri! must be minify then as async defer is set by our plugin (that should be updated to just defer as we've removed async from our website too). would be amazing to get this fix in the next release as WP Rocket is very popular so happens often! thanks!

**Comment by iamkingsleyf** [comment]
This explains why it stopped working

**Comment by metmarkosaric** [comment]
sorry for the inconvenience @iamkingsleyf! it looks like WP Rocket had an update recently that changed something in the way it works so their plugin is now again causing issues for our tracking. we will hopefully find a way to fix it in our next release. in the meanwhile you should be able to whitelist our domain/script in WP Rocket settings so they don't touch it. thanks!

**Comment by iamkingsleyf** [comment]
> sorry for the inconvenience @iamkingsleyf! it looks like WP Rocket had an update recently that changed something in the way it works so their plugin is now again causing issues for our tracking. we will hopefully find a way to fix it in our next release. in the meanwhile you should be able to whitelist our domain/script in WP Rocket settings so they don't touch it. thanks!

i switched to script for some sites, let me whitelist them

**Comment by metmarkosaric** [comment]
Another report of a site not tracking today and the snippet was like this in the source code:

`<script data-minify="1" type='text/javascript' async defer data-domain='yourdomain.com' data-api='https://plausible.io/api/event' src='https://yourdomain.com/wp-content/cache/min/1/js/plausible.outbound-links.js?ver=1665422031' id='plausible-analytics-js'>
</script> `

The snippet in our WP plugin without any WP Rocket and other performance optimization plugin conflicts looks like this:

`<script async defer data-domain='yourdomain.com' data-api='https://plausible.io/api/event' src='https://plausible.io/js/plausible.outbound-links.js?ver=1.2.4' id='plausible-analytics-js'></script>`

So what breaks tracking? It's either the data-minify="1" part or the fact that our script ends up being run from a first party domain or that they add a different ?ver= at the end even!? Would be nice if you can test and confirm what's happening @bouchaala-sabri. Thanks!

**Comment by bouchaala-sabri** [comment]
a fix will be included in the next release.

**Comment by metmarkosaric** [comment]
amazing news @bouchaala-sabri!

**Comment by metmarkosaric** [comment]
New WordPress plugin release is now out! See https://wordpress.org/plugins/plausible-analytics/

We now automatically whitelist our script in WP Rocket settings

**Comment by Dan0sz** [comment]
Yes, the whitelisting happens through a filter. You won't see it show up in WP Rocket's settings area, to clarify.
