### ISSUE TITLE
plausible.io refused to connect to WP Analytics Dashboard

### ISSUE THREAD

**Issue by Daniel-GRD** [plausible/wordpress#42]
After filling out the shared link and saving it in the settings the data doesn't show in the WP Analytics dashbaord. Any ideas what the issue could be?

![image](https://user-images.githubusercontent.com/86793668/124154223-96357480-da95-11eb-8307-6299d8ea7636.png)

**Comment by metmarkosaric** [comment]
This happens when you try to embed a password protected shared link. Please do keep the password field blank when creating a shared link for embed purposes as it's not possible to embed a password-protected dashboard.

**Comment by Daniel-GRD** [comment]
Thank you for your quick help! This solved my issue.

**Comment by metmarkosaric** [comment]
you're welcome! thanks for the update!
