### ISSUE TITLE
Analytics not showing in WP Dashboard

### ISSUE THREAD

**Issue by Kyrena5** [plausible/wordpress#43]
I've just installed the plausible plugin and insert a shared link, activated "View your stats in your WordPress dashboard.
"saved, went to dashboard/Analytics, and nothing was there. There were only two buttons on the top right. Since I assume that I'm dealing with a bug, I hit the button "report bug."  Maybe I'm just too unfamiliar with the timing of the dashboard showing up; perhaps I should have given it more time after refreshing the page several times; maybe it's a bug. I don't know. It would be nice for the dashboard to show up. - I hope this info helps.

**Comment by metmarkosaric** [comment]
Could you share a screenshot perhaps of what it looks like?

One common occurrence for the stats not showing is when you try to embed a password protected shared link. Please do keep the password field blank when creating a shared link for embed purposes as it's not possible to embed a password-protected dashboard.

**Comment by Kyrena5** [comment]
Oh, That's what I did. I've used a password-protected shared link. I'm going to change this now and let you know ASAP - thank you for your quick response

**Comment by Kyrena5** [comment]
Perfect, everything is working now when using a shared link without a password. The dashboard is showing now. - Thank you so much

**Comment by metmarkosaric** [comment]
great, thanks for the update! enjoy Plausible!
