### ISSUE TITLE
Issue with the Photonic Lightbox plugin

### ISSUE THREAD

**Issue by metmarkosaric** [plausible/wordpress#48]
"I'm using Plausible Analytics Wordpress plugin and [a Photonic plugin](https://wordpress.org/plugins/photonic/) showing Google Photos in a Lightbox malfunctions when your plugin is active. It loads the url of the picture shown in the Lightbox in the browser window instead of just showing it in the Lightbox. Can this be prevented?"

**Comment by mehul0810** [comment]
@metmarkosaric Is it possible to get a short video or screenshot about the issue? As far as I can assume we only have analytics JS included in the plugin, so there should be negligible chances of a conflict with the lightbox of the Photonic plugin.

**Comment by metmarkosaric** [comment]
thanks for the quick reply @mehul0810! it seems to be working all fine now after they deactivated a caching plugin. they seem to be using WP Super Cache and looking at Photonic plugin reviews there are many reports of issues with caching so I suspect this is what it was. i'll close this for now unless we get more details that point in the direction that it may be caused by Plausible plugin itself rather than caching
