### ISSUE TITLE
Conflict with performance optimization plugins

### ISSUE THREAD

**Issue by metmarkosaric** [plausible/wordpress#49]
We regularly hear reports about our script being changed and affected by performance optimization plugins. Some example:

* A case yesterday where our WP plugin snippet in the source code was changed automatically and is not able to track. The source code ended up looking like this. The site is using WP Rocket and Ezoic without any other plugins.

`<link rel="dns-prefetch" href="//plausible.io"/>`

* Another case is Siteground Optimizer. We now have [these instructions](https://plausible.io/wordpress-analytics-plugin#conflict-with-siteground-optimizer) from SG on how to fix it. With SG Optimizer and our plugin, it's not possible to see any Plausible snippet in the source code and tracking doesn't work so people need to take the manual action above to fix it.

Possible solutions?

1. Ideally we would make our plugin introduce a WordPress proxy by default for all users. That may prevent these things as there won't be any visible codes to Plausible or any third party domains anywhere so hopefully these plugins would stop "optimizing" things
2. As an alternative, if it's possible it would be nice to do some tweak to tell other plugins not to touch our script

**Comment by ukutaht** [comment]
For context, the reason for most breakage seems to be that our script relies on `document.currentscript` to read the origin of the script so it can send the events to the same origin. Site optimizers seem to change the origin so the script isn't loaded from `src="plausible.io/js/plausible.js"` but rather from `src="site-optimizer-cdn.com/js/[file-hash].js` or something like that. This results in us trying to send the event to `site-optimizer-cdn.com/api/event` which doesn't exist.

**Comment by metmarkosaric** [comment]
closing this as we've improved the plugin to mitigate this plus [documented](https://plausible.io/wordpress-analytics-plugin#ive-installed-plausible-but-stats-dont-track) all the issues and explained how to solve them. and we're also moving to a proxy by default in the next version which should limit any possible issues too

**Comment by johnxie** [comment]
> closing this as we've improved the plugin to mitigate this plus [documented](https://plausible.io/wordpress-analytics-plugin#ive-installed-plausible-but-stats-dont-track) all the issues and explained how to solve them. and we're also moving to a proxy by default in the next version which should limit any possible issues too

This will be very exciting, for now the cloudflare worker snippet would work correctly for WP?

**Comment by metmarkosaric** [comment]
yes, you can follow our Cloudflare instructions and use that proxy on WP too

**Comment by metmarkosaric** [comment]
New WordPress plugin release is now out! See https://wordpress.org/plugins/plausible-analytics/

We now automatically whitelist our script in WP Rocket

**Comment by Dan0sz** [comment]
Shouldn't we reopen this? In the current release only WP Rocket was added in #38. I wasn't aware of any issue with SG Optimizer.

**Comment by metmarkosaric** [comment]
yes SG Optimizer has a similar issue

**Comment by bouchaala-sabri** [comment]
similar issues may happen with many other cache plugins. fixes to most of the popular ones can be imported from this file https://github.com/bouchaala-sabri/plausible-analytics-wordpress/blob/feature/proxy/src/Includes/ThirdParties.php

**Comment by johnxie** [comment]
Looking good so far on https://www.taskade.com/blog

**Comment by Dan0sz** [comment]
Hi @johnxie, thanks for the feedback! Which optimisation plugin are you using?

**Comment by johnxie** [comment]
WPRocket

**Comment by Dan0sz** [comment]
WP Optimize should be on this list as well: https://github.com/plausible/wordpress/issues/111

**Comment by Dan0sz** [comment]
WP Optimize and SiteGround Optimizer compatibility will be added in 1.3.0. PR is soon to follow.

**Comment by Dan0sz** [comment]
https://github.com/plausible/wordpress/pull/123 takes care of this.

**Comment by Dan0sz** [comment]
If you're running into issues with other optimization plugins than WP Rocket, SG Optimizer or WP Optimize, please open a new issue.

**Comment by Swiss-Mac-User** [comment]
> #123 takes care of this.

@Dan0sz this means, upon updating the WP Plugin, it is safe to remove any exclusions to the Plausible JS from WP Optimize; right?
