### ISSUE TITLE
Plausible is blocked in Wordpress dashboard

### ISSUE THREAD

**Issue by froart** [plausible/wordpress#52]
![image_2021-10-29_060244](https://user-images.githubusercontent.com/22843145/139366726-9ca2cd6f-72b4-4360-8a97-ff631465eb70.png)

Good day, I have put the shared link to the Wordpress Plausible plugin settings as stated in the instruction, but i receive this ^. What is wrong? Thank you

**Comment by metmarkosaric** [comment]
closing this for now

**Comment by froart** [comment]
What do you mean shared link? Do you mean page / post?

**Comment by froart** [comment]
It worked, thank you.

**Comment by metmarkosaric** [comment]
thanks for the update @froart!
