### ISSUE TITLE
No Plausible dashboard when WordPress is installed in subdirectory 

### ISSUE THREAD

**Issue by philbraun** [plausible/wordpress#53]
When WP is running in a subdirectory, like with roots.io Bedrock (mydomain.com/wp/wp-admin/), Plausible WP plugin doesn't seem to be able to connect to plausible for displaying the embedded analytics.
The site code used in plausible is mydomain.com%2Fwp, but from the WordPress side this probably gets interpreted as mydomain.com/wp, which results in an 404 on plausible.

**Comment by MacStasy** [comment]
The same thing happens when you have the wordpress installation in a subdirectory in my case /site/ but the domain points to that subdirectory without /site/ in your url.

**Comment by soderlind** [comment]
@Dan0sz  We're having the "same" problem, adding Plausible to subsites on a WordPress multisite with  /subsite.

Our issue here is that the `%2f` is stripped away when I save the shared link.

Btw, we're developing a multisite add-on for plausible, making it easy to activate/deactivate plausible pr site (we have 120+ sites). I'll make the multisite plugin public available when it's done.

Btw2, our `get_domain` looks like this:

```php
// Use domain mapping domain if exists, else get from standard WP settings.
if ( \function_exists( '\domain_mapping_siteurl' ) && 'NA' !== \domain_mapping_siteurl( 'NA' ) ) {
	$default_settings['domain_name'] = \domain_mapping_siteurl( false );
} elseif ( \function_exists( '\get_site' ) ) {
	// Multi site, get from blogs table.
	$site = \get_site();
	if ( $site instanceof \WP_Site ) {
		$default_settings['domain_name'] = \untrailingslashit( $site->domain . $site->path );
	}
} else {
	// single site, get from options table.
	$url                             = \get_option( 'home' );
	$default_settings['domain_name'] = \preg_replace( '/^http(s?)\:\/\/(www\.)?/i', '', $url );
}

$plausible_analytics_settings = \array_merge( $plausible_analytics_settings, $default_settings );
\update_option( 'plausible_analytics_settings', $plausible_analytics_settings ); // update with new options.

```

**Comment by soderlind** [comment]
@metmarkosaric Being impatient, have to deploy to prod soon, here's a quick fix:  https://gist.github.com/soderlind/6d6735baeab379b4d7e1e5497cd8581b

**Comment by soderlind** [comment]
@Dan0sz May I suggest that you replace `Helpers::clean` with the following:

```php
public static function clean( $var ) {
	// If the variable is an array, recursively apply the function to each element of the array
	if ( is_array( $var ) ) {
		return array_map( [ __CLASS__, __METHOD__ ], $var );
	}

	// If the variable is a scalar value (string, integer, float, boolean).
	if ( is_scalar( $var ) ) {
		// Parse the variable using the wp_parse_url function.
		$parsed = wp_parse_url( $var );
		// If the variable has a scheme (e.g. http:// or https://), sanitize the variable using the esc_url_raw function.
		if ( isset( $parsed['scheme'] ) ) {
			return esc_url_raw( wp_unslash( $var ), [ $parsed['scheme'] ] );
		}
		// If the variable does not have a scheme, sanitize the variable using the sanitize_text_field function
		return sanitize_text_field( wp_unslash( $var ) );
	}

	// If the variable is not an array or a scalar value, return the variable unchanged.
	return $var;
}
```

**Comment by Dan0sz** [comment]
Hi @soderlind!


Thanks for the suggestion. Can you make a PR? Saves a lot of time. Please also explain the improvements compared to the previous approach (my predecessor wrote that code, so I haven't studied it yet)

**Comment by soderlind** [comment]
btw, using `esc_raw_url` will preserve `%2f`, my code above was correct.
