### ISSUE TITLE
Added French translation of the plugin

### ISSUE THREAD

**Issue by elodiew** [plausible/wordpress#54]
Hello,

I would like to propose a French translation of the WordPress plugin.
How can I do this?

Thanks for your feedback

Best regards

**Comment by mehul0810** [comment]
Hi @elodiew 

Thanks for reaching out and adding your feature request to add French translation to the plugin.

You can add the translation to the plugin using the below links:
**French (Belgium):** https://translate.wordpress.org/projects/wp-plugins/plausible-analytics/stable/fr-be/default/
**French (Canada):** https://translate.wordpress.org/projects/wp-plugins/plausible-analytics/stable/fr-ca/default/

Once the translation has reached 100% for a specific language, it would be easy to translate the language of the plugin to French.

Let me know if you have any further questions.

Thanks!

**Comment by elodiew** [comment]
Hi !

Great,
I just added the translation under azurwebdesign.

I also sent the .po & .mo files in French.

Hope this helps you ...

Other choices, is there a way to translate the analytics data in the WP back office?

Example for:
UNIQUE VISITORS
TOTAL PAGES VIEWED
ETC ...
![2](https://user-images.githubusercontent.com/50192304/141762602-b95a38a7-f90c-4f23-b5b2-724972ddce56.jpg)

I'm French so sorry for my bad English :)


Thanks for your feedback

**Comment by metmarkosaric** [comment]
that's not possible at this time unfortunately @elodiew. Plausible is English only at the moment. please subscribe to this thread so you can follow our progress on making Plausible multilingual: https://github.com/plausible/analytics/discussions/354
