### ISSUE TITLE
Wordpress dashboard quit working after new self-hosting install

### ISSUE THREAD

**Issue by widener-physics** [plausible/wordpress#55]
I have a wordpress site w/ self-hosted Plausible.  Previously the dashboard plugin was working fine.

Yesterday, I moved my Plausible install to a new VPS.  Plausible itself works fine, and it correctly records and displays traffic on the site dashboard.

However my Wordpress plugin has stopped working.  I created a new shared link and pasted that into the plugin, and all I see is a blank box.  No other plugins have changed, so I doubt there is a conflict.

Any ideas?

edit: I created a (hidden) page on my site and used the embed code with the shared link, and it worked fine.  So I'm not sure why the WP plugin doesn't work.  Nothing else has changed, I just replaced the shared link w/ one from the new site.  The hostname and everything else are the same.

**Comment by ukutaht** [comment]
Any console errors on the page where the embed is supposed to load?

**Comment by widener-physics** [comment]
Console showed the following error (domain name changed for privacy):

`Mixed Content: The page at 'https://example.com/wp-admin/index.php?page=plausible-analytics-statistics' was loaded over HTTPS, but requested an insecure frame 'http://pl.example.com/share/example.com?auth=tuYutgbCOceJ4wGyto2Vn&embed=true&theme=light&background=transparent'. This request has been blocked; the content must be served over HTTPS.
`
I am running Plausible behind a Caddy reverse-proxy server which automatically issues an SSL cert.  However the shared link defaulted to http.  Even though Caddy is supposed to redirect to https, maybe the plugin didn't like the http.  So I changed the shared link to https and it all works properly now!

**Comment by ukutaht** [comment]
Great to hear you got it working!
