### ISSUE TITLE
Proxy scripts and events

### ISSUE THREAD

**Issue by wiesson** [plausible/wordpress#57]
https://plausible.io/docs/proxy/introduction#are-you-concerned-about-missing-data

```
https://<yourdomain.com>/js/script.js -> https://plausible.io/js/plausible.js
https://<yourdomain.com>/api/event    -> https://plausible.io/api/event
```

How can I tell the plausible wordpress plugin that I have added the proxy routes? Should I just add it to the template manually and skip the wp plugin?

**Comment by metmarkosaric** [comment]
Yes, please add the snippet manually without the plugin for now. We'll try and support the proxy by default in the next version of the plugin. Thanks!

**Comment by wiesson** [comment]
Awesome! :)

I go the manual way, it was just convenient to use the official plugin.
