### ISSUE TITLE
Excluding Pages

### ISSUE THREAD

**Issue by dserv-nh** [plausible/wordpress#58]
Similar to https://plausible.io/docs/excluding-pages
Am I missing something, or is this not possible with the WordPress plugin?

**Comment by metmarkosaric** [comment]
no problem! and sure, we welcome any contribution. thank you!

**Comment by metmarkosaric** [comment]
New WordPress plugin release is now out! See https://wordpress.org/plugins/plausible-analytics/

You can now exclude pages from being tracked
