### ISSUE TITLE
"Plausible.io refused to connect": Analytics not loading on wordpress dashboard 

### ISSUE THREAD

**Issue by Pol-Lanski** [plausible/wordpress#61]
I'm getting a nasty refused to connect message when trying to access the analytics on the wordpress dashboard:
<img width="338" alt="Screenshot 2022-03-11 at 15 39 50" src="https://user-images.githubusercontent.com/19168735/157888655-0385692c-3e6f-4b47-bf87-9d5cd6d7adeb.png">

Browser console shows: `Refused to display 'https://plausible.io/' in a frame because it set 'X-Frame-Options' to 'sameorigin'.`

**Comment by metmarkosaric** [comment]
hi @Pol-Lanski! this normally happens when you try to embed a password-protected shared link. you would need to embed a shared link without a password. see https://plausible.io/docs/embed-dashboard

**Comment by Pol-Lanski** [comment]
This worked! Thanks :)

**Comment by metmarkosaric** [comment]
great! thanks for the update!
