### ISSUE TITLE
Make analytics page visible to non-admins

### ISSUE THREAD

**Issue by viktorstrate** [plausible/wordpress#62]
It would be nice if the `Dashboard > Analytics` page could be enabled for non-admin users.

Maybe as a custom capability: https://wordpress.org/support/article/roles-and-capabilities/

**Comment by masteradhoc** [comment]
@viktorstrate this is already developed in #35 just not released yet im afraid

**Comment by metmarkosaric** [comment]
hopefully soon! stay tuned! i'll close this as there's that other thread already

**Comment by viktorstrate** [comment]
Thank you 👍

**Comment by metmarkosaric** [comment]
New WordPress plugin release is now out! See https://wordpress.org/plugins/plausible-analytics/

You can now allow selected user roles to access the stats dashboard
