### ISSUE TITLE
Security issue and status update?

### ISSUE THREAD

**Issue by spetrey** [plausible/wordpress#69]
I saw the notice on the [plugin page](https://wordpress.org/plugins/plausible-analytics/):
> This plugin has been closed as of April 7, 2022 and is not available for download. This closure is temporary, pending a full review.

Then I found [this thread](https://wordpress.org/support/topic/whats-the-status-of-the-security-issue/#post-15588132) with more details:

> Our WordPress developers have already submitted a new version of the plugin to the WordPress team for review. These things will take a bit more time before the new plugin will go live. The vulnerability reported only happens if an unauthorized person has gained control over the WordPress admin panel. Otherwise, the vulnerability can’t happen.
>
> If this causes an issue for you, please use the manual way to insert our snippet to your site while we’re fixing the plugin: https://plausible.io/docs/plausible-script. You could also use a plugin such as this one if you prefer to install Plausible using a plugin: https://wordpress.org/plugins/insert-headers-and-footers/
>
> Thanks for your patience and sorry for the inconvenience!

It could be helpful to add a notice to the README and/or to [the marketing page](https://plausible.io/wordpress-analytics-plugin) that is promoting the plugin.

Related: #64

**Comment by metmarkosaric** [comment]
thanks for the feedback @spetrey! there's already a thread on this topic with updates: https://github.com/plausible/wordpress/issues/64

**Comment by spetrey** [comment]
Thanks for the updates! Y’all are awesome 😊

**Comment by metmarkosaric** [comment]
thank you!

**Comment by metmarkosaric** [comment]
Our plugin is now back in the WordPress plugin repository. Thank you for your patience!

**Comment by spetrey** [comment]
thanks @metmarkosaric! 🙌

**Comment by metmarkosaric** [comment]
you're welcome! enjoy!
