### ISSUE TITLE
Settings don't seem to be saved

### ISSUE THREAD

**Issue by metmarkosaric** [plausible/wordpress#72]
On the brand new version, none of the optional settings seem to be working. You can enable and save options such as "View your stats in your WordPress dashboard" and it looks all fine. But nothing actually happens and when you return back to the plugin settings page, the settings you enabled previously are no longer enabled.

**Comment by masteradhoc** [comment]
following as we have this issue.

**Comment by louisefindlay23** [comment]
Chiming as +1. I have the same issue.

**Comment by Ankur0812** [comment]
I solved #72 bug and generate PR for that & send to mehul.

**Comment by metmarkosaric** [comment]
> I solved #72 bug and generate PR for that & send to mehul.

great stuff @Ankur0812, thanks!

**Comment by masteradhoc** [comment]
Any update here?

**Comment by metmarkosaric** [comment]
hi @masteradhoc! @mehul0810 will review the fixes as soon as possible and then we'll make it live to the wordpress plugin directory. we'll update here as soon as it's done. thanks for your patience!

**Comment by Dan-Sun** [comment]
Is today as soon as possible? =)

**Comment by metmarkosaric** [comment]
Don't think it will be done today, sorry @Dan-Sun. There's more work to be done in order to fix this issue unfortunately. We'll update as soon as we have some new info.

**Comment by mehul0810** [comment]
Closing this in favor of release `1.2.4`

**Comment by metmarkosaric** [comment]
great stuff, thanks @mehul0810!
