### ISSUE TITLE
WP Dashboard not working

### ISSUE THREAD

**Issue by JohnSharkey** [plausible/wordpress#73]
Hello.

When I try to get Plausible to work in WP, with the dashboard feature, I enter the shared link created from the system, click the "View your stats in your WordPress dashboard" toggle in the WP app, hit save, but the toggle does not stick, and the dashboard doesn't show.

**Comment by metmarkosaric** [comment]
thanks for reporting @JohnSharkey and sorry for the inconvenience! we just released a new version of the plugin yesterday and this is a new bug that we will fix as soon as possible. there's already a thread for this issue here: https://github.com/plausible/wordpress/issues/72

**Comment by mehul0810** [comment]
Closing this in favor of release `1.2.4`
