### ISSUE TITLE
View your stats in your WordPress dashboard setting ineffective

### ISSUE THREAD

**Issue by jazibobs** [plausible/wordpress#75]
Hi all, 

I'm currently trying to add the Plausible analytics to my Wordpress admin dashboard but when I add a shared link and then save my settings nothing appears to happen. Are you able to advise on why this may be the case?

I'm running version 1.2.3 of the Plausible WordPress plugin on version 5.9.3 of WordPress. The website is https://www.wowenglish.co.uk

Many thanks for your help.

**Comment by metmarkosaric** [comment]
thanks for reporting @jazibobs! this is a bug and we already have a fix coming very shortly. there's a thread with this topic already: https://github.com/plausible/wordpress/issues/72

**Comment by jazibobs** [comment]
Thanks for the fast response, much appreciated.

**Comment by mehul0810** [comment]
Closing this in favor of release `1.2.4`
