### ISSUE TITLE
Include Editors in the Default Non-Tracking

### ISSUE THREAD

**Issue by louisefindlay23** [plausible/wordpress#76]
Currently, logged-in adminstators aren't tracked by Plausible but it would be great if there was an option to include Editors as well since often clients are given the Editor role rather than administrator.

**Comment by metmarkosaric** [comment]
thanks for the feedback @louisefindlay23! this will be coming in the next major release of the plugin. the work has already started. see https://github.com/plausible/wordpress/pull/51

**Comment by sascha-bleech** [comment]
We are nearly a year on, this has been marked as closed, but nothing has been released. It makes plausible unusable for me as I do not want to give all site users admin rights only to view some statistics.

**Comment by metmarkosaric** [comment]
New WordPress plugin release is now out! See https://wordpress.org/plugins/plausible-analytics/

You can now exclude user roles from being tracked
