### ISSUE TITLE
Outbound links not found

### ISSUE THREAD

**Issue by paulasasseron** [plausible/wordpress#83]
My website network is appointing an error on the outbound links:

_URL da Solicitação: https://https//plausible.io.monde.com.br/js/plausible.outbound-links.js?ver=1.2.4
Política de referenciador: strict-origin-when-cross-origin_

I'm using Plausible plugin on Wordpress and it is duplicating the "https". If I fix the link and open it in browser, it won't open, instead it shows 404 error.

Is this my setting or a bug on the plugin?

**Comment by metmarkosaric** [comment]
Our team needed some more info to get to the bottom of this, however we've not heard back from you and we cannot replicate this issue ourselves. We're going to close this for now, but let us know if you manage to dig up some more info and we'll reopen.
