### ISSUE TITLE
On narrow screens the wordpress analytics dashboard is too wide 

### ISSUE THREAD

**Issue by larsschellhas** [plausible/wordpress#86]
I'm using a Nokia 8 Sirroco. Here are the screen informations: https://www.sizescreens.com/nokia-8-sirocco-screen-specifications/

![image](https://user-images.githubusercontent.com/14281234/177830824-796da0ba-1c80-4941-8397-b0784156a9b4.png)

**Comment by metmarkosaric** [comment]
thanks for reporting @larsschellhas!

**Comment by Dan0sz** [comment]
I can no longer replicate this issue in our latest beta:

![afbeelding](https://github.com/plausible/wordpress/assets/18595395/307b4fc1-b0bd-4bc8-bc2a-9f4badc76a80)

Can you, @metmarkosaric?

Might've been a change in the dashboard's CSS, not related to the WordPress plugin. Maybe?

**Comment by metmarkosaric** [comment]
closing this for now as we cannot replicate it
