### ISSUE TITLE
The analytics dashboard not showing.  It shows that "plausible.io refused to connect."

### ISSUE THREAD

**Issue by vimalroy** [plausible/wordpress#94]

**Comment by metmarkosaric** [comment]
hi @vimalroy! are you trying to embed a password protected dashboard? this error normally shows for that. try to create a non-password protected shared link

**Comment by vimalroy** [comment]
Yes. It worked. Thank you for your support.

**Comment by vimalroy** [comment]
Yes. It worked. Thank you for your support.

**Comment by metmarkosaric** [comment]
great! thanks for the update!
