### ISSUE TITLE
Integrate tagged-events

### ISSUE THREAD

**Issue by metmarkosaric** [plausible/wordpress#95]
hi @bouchaala-sabri! @RobertJoonas is finishing the work on [our new tagged-events script](https://github.com/plausible/analytics/pull/2333). I've just tested it today and it works great so we're hoping to make it live very soon. It makes setting up custom events for things such as button clicks, form completions, purchases/orders etc so much easier. 

On WP, you will now only need to tag a specific element using the WP UI for tracking to work. Like this:

![Screenshot from 2022-10-26 13-35-44](https://user-images.githubusercontent.com/34340819/198016404-212d1403-22a4-4a37-8c9d-7e0b1d6603bd.png)

Compared to our current method of setting up events, in the new script there are no extra lines needed to add to the snippet, no extra code needed to add to the page where the goal is and no need to tag any specific element using HTML. Easy enough even for me! :)

So we should integrate this by default into our WP plugin. From what I see, we only need to change the snippet that we use in the plugin for this to work. We currently use: `plausible.outbound-links.js`. To enable tagged-events, we need to use `script.tagged-events.outbound-links.js` instead (we currently recommend script.js rather than plausible.js so we can change that too at the same time)

Our WP plugin already automatically adds that second line to the snippet (`<script>window.plausible = window.plausible || function() { (window.plausible.q = window.plausible.q || []).push(arguments) }</script>`) and I don't think we can remove that because it is necessary to get the 404 error page tracking. Robert can confirm.

**Comment by RobertJoonas** [comment]
As we want to have our default script as small in size as possible, we should make `tagged-events` an opt-in feature in the plugin. (it would roughly double the script size). I believe the choice menu for enabling script extensions is already implemented, so shouldn't be a problem to add this one in there. And yes, the plugin would only have to handle adding the extension in the script filename, nothing else.

> Our WP plugin already automatically adds that second line to the snippet (<script>window.plausible = window.plausible || function() { (window.plausible.q = window.plausible.q || []).push(arguments) }</script>) and I don't think we can remove that because it is necessary to get the 404 error page tracking. Robert can confirm.

Yes, this is needed for 404 tracking. And also, with this snippet, clients will be able to use the `plausible()` function themselves to trigger custom events with JavaScript. I don't think we should remove it.

**Comment by metmarkosaric** [comment]
New WordPress plugin release is now out! See https://wordpress.org/plugins/plausible-analytics/

Custom events can now be setup using CSS class names
