### ISSUE TITLE
Add option to not track logged in users

### ISSUE THREAD

**Issue by bdlowery** [plausible/wordpress#97]
I work on a site where 25-ish logged in users view the site 20-30 times per day. 
There is currently a setting "Track analytics for administrator". This is great, but I'd like to be able to select certain user-roles, or even just have an option to not track _anyone_ logged in.

**Comment by sascha-bleech** [comment]
Would be great to see this landing soon.

**Comment by metmarkosaric** [comment]
New WordPress plugin release is now out! See https://wordpress.org/plugins/plausible-analytics/

You can now exclude different user roles from being tracked
