### ISSUE TITLE
Next release of the plugin

### ISSUE THREAD

**Issue by sascha-bleech** [plausible/wordpress#99]
Hi there,
do you have any ETA for the next release of the plugin? There seems a lot of functionality that users are waiting for nearly a year now inside the develop branch. Would be great to get that released soon.
Basically I need to decide if I cancel my free trial or become a subscriber as at the current state I cannot use the plugin.

**Comment by metmarkosaric** [comment]
thanks for reaching out @sascha-bleech! we started working with a new WP developer this week hoping to make some progress with our plugin. as you say, there are several unreleased features that we will focus on first. but i cannot make any promise on when the next release will be ready to go live. thanks for your patience!

**Comment by metmarkosaric** [comment]
New WordPress plugin release is now out! See https://wordpress.org/plugins/plausible-analytics/

Highlights:

1. File downloads included alongside external link click and 404 error page tracking
2. Custom events can now be setup using CSS class names
3. Exclude pages and user roles from being tracked
4. Allow selected user roles to access the stats dashboard
5. See a link to the post stats in the toolbar while browsing your site
